### ISSUE TITLE
Написать техническое задание

### ISSUE THREAD

**Issue by wldmr-key** [morzav/growbox#2]
Текущая версия вполне хороша, но из нее не очень понятен интерфейс человека, который, как ты пишешь "не должен обладать практическими навыками работы с системой ввиду низкого порога вхождения". Думаю, необходимо, чтобы обвязка микроконтроллера предполагала сетевое взаимодействие (IOT ?)
Тогда логично было бы озадачится управлением микроконтроллером либо по домашней сети, либо посредством интернет-сервиса. Второе прикольнее

И, лучше в процессе обсуждения документа выкладывать его не в середину репозитория, а сюда - в аттачменты.
[ТЗ_РПС.docx](https://github.com/morzav/growbox/files/3613503/_.docx)

**Comment by morzav** [comment]
Управление системой планируется реализовать посредством мобильного приложения, которое  подключено к микроконтроллеру по Bluetooth. Если получится подружить систему с wifi, то так и сделаю, единственной проблемой, исходя из открытых источников, является плохое качество исполнения модуля wifi. 
[ТЗ_РПС_v2.docx](https://github.com/morzav/growbox/files/3626136/_._v2.docx)

**Comment by wldmr-key** [comment]
вот и готовая проблема для исследовательской части ))
